name: Deploy Laravel to CPanel via FTP

on:
  push:
    branches:
      - main  # Trigger deployment when there's a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout code from your GitHub repository

    - name: Set up PHP
      uses: shivammathur/setup-php@v2  # Set up PHP
      with:
        php-version: '8.2'  # Specify the PHP version you're using

    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Deploy to CPanel via FTP using lftp
      env:
        FTP_SERVER: ${{ secrets.SERVER }}
        FTP_USERNAME: ${{ secrets.USERNAME }}
        FTP_PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        lftp -u $FTP_USERNAME,$FTP_PASSWORD -p 21 $FTP_SERVER <<EOF
        set ftp:ssl-allow no
        mirror -R --verbose ./ /public_html/
        quit
        EOF
